spring:
  application:
    name: ttalkkak-notify

webhook:
  jira:
    secret: ${JIRA_WEBHOOK_SECRET}
  confluence:
    secret: ${CONFLUENCE_WEBHOOK_SECRET}

discord:
  webhook:
    task: ${DISCORD_WEBHOOK_URL_TASK}
    docs: ${DISCORD_WEBHOOK_URL_DOCS}

chat:
  broker:
    url: ${CHAT_URL}
    token: ${CHAT_BROKER_TOKEN}
    target: ${CHAT_TARGET}

confluence:
  api:
    email: ${CONFLUENCE_API_EMAIL}
    token: ${CONFLUENCE_COMMENT_READ_API_TOKEN}
