package com.ttalkkak.notify.notification;

public enum EventType {
    JIRA_ISSUE_CREATED,
    JIRA_ASSIGNEE_CHANGED,
    JIRA_STATUS_CHANGED,
    JIRA_COMMENT_CREATED,
    CONFLUENCE_PAGE_CREATED,
    CONFLUENCE_PAGE_UPDATED,
    CONFLUENCE_LIVE_DOC_CREATED,
    CONFLUENCE_COMMENT_CREATED
}
